// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLxZB6p69pEDkiPdlEha0hNAoCoatI5hI',
    appId: '1:217450363067:web:6b64525e8beeefc03e519e',
    messagingSenderId: '217450363067',
    projectId: 'book-reader-547bc',
    authDomain: 'book-reader-547bc.firebaseapp.com',
    storageBucket: 'book-reader-547bc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGHBEEFhP1Y348yz5RCpNXjQkV5gOrl_s',
    appId: '1:217450363067:android:237b14dd5c42a35d3e519e',
    messagingSenderId: '217450363067',
    projectId: 'book-reader-547bc',
    storageBucket: 'book-reader-547bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5D_g7sEFUjBYIUhLLadsbUtVDgB8KsSM',
    appId: '1:217450363067:ios:a6f8069115d324aa3e519e',
    messagingSenderId: '217450363067',
    projectId: 'book-reader-547bc',
    storageBucket: 'book-reader-547bc.firebasestorage.app',
    iosBundleId: 'com.example.bookapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5D_g7sEFUjBYIUhLLadsbUtVDgB8KsSM',
    appId: '1:217450363067:ios:a6f8069115d324aa3e519e',
    messagingSenderId: '217450363067',
    projectId: 'book-reader-547bc',
    storageBucket: 'book-reader-547bc.firebasestorage.app',
    iosBundleId: 'com.example.bookapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLxZB6p69pEDkiPdlEha0hNAoCoatI5hI',
    appId: '1:217450363067:web:2fe9e145aec15da63e519e',
    messagingSenderId: '217450363067',
    projectId: 'book-reader-547bc',
    authDomain: 'book-reader-547bc.firebaseapp.com',
    storageBucket: 'book-reader-547bc.firebasestorage.app',
  );

}